# Generated by Django 5.2.7 on 2025-10-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('ProductoListView', 'Puede ver la sección de productos')]},
        ),
    ]
